// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMZI0BKCimIkGj2JMQG3rmwqvmL_n6Lok',
    appId: '1:585228689479:web:133a3f03cf12385a9c1162',
    messagingSenderId: '585228689479',
    projectId: 'akilliotopark-ddfa7',
    authDomain: 'akilliotopark-ddfa7.firebaseapp.com',
    storageBucket: 'akilliotopark-ddfa7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcQdSQDlf811jqJV7D6XnLhFrZes-x1F4',
    appId: '1:585228689479:android:d50117b22373768c9c1162',
    messagingSenderId: '585228689479',
    projectId: 'akilliotopark-ddfa7',
    storageBucket: 'akilliotopark-ddfa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUzanuslVLdwEYTbpjz2FatRGUEahYZ_8',
    appId: '1:585228689479:ios:42798ff7abd9cee29c1162',
    messagingSenderId: '585228689479',
    projectId: 'akilliotopark-ddfa7',
    storageBucket: 'akilliotopark-ddfa7.appspot.com',
    iosBundleId: 'com.example.uygulamaflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUzanuslVLdwEYTbpjz2FatRGUEahYZ_8',
    appId: '1:585228689479:ios:42798ff7abd9cee29c1162',
    messagingSenderId: '585228689479',
    projectId: 'akilliotopark-ddfa7',
    storageBucket: 'akilliotopark-ddfa7.appspot.com',
    iosBundleId: 'com.example.uygulamaflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMZI0BKCimIkGj2JMQG3rmwqvmL_n6Lok',
    appId: '1:585228689479:web:cf59c41f3b9a57e29c1162',
    messagingSenderId: '585228689479',
    projectId: 'akilliotopark-ddfa7',
    authDomain: 'akilliotopark-ddfa7.firebaseapp.com',
    storageBucket: 'akilliotopark-ddfa7.appspot.com',
  );
}
